### ISSUE TITLE
ddskk 16.1

### ISSUE THREAD

**Issue by tkita** [chuntaro/NTEmacs64#4]
Emacs 25.1 のバイナリを使わさせていただきます。ありがとうございます。
README に「DDSKK はバージョン 15.2 以降を使用してください」と記載あります。
実用上は問題ないのですが、Emacs 25 で ddskk 15.2 をバイトコンパイルすると、
ワーニングが表示されます。
```
In skk-search-function-usage:
skk.el:4734:27:Warning: `help-make-usage' is an obsolete function (as of
    25.1); use `help--make-usage' instead.
```
ddskk 16.1 で対処済ですので、README を修正していただければと思います。

**Comment by chuntaro** [comment]
連絡ありがとうございます。
バージョン表記を修正しました。
